### ISSUE TITLE
Provide a single command to generate both root and developer certificate

### ISSUE THREAD

**Issue by wbachnik** [dynatrace-oss/dt-cli#11]
For simpler use cases it would be much more convenient to have a single command (e.g. `gencerts`) that would create both root and developer certificates so that the user doesn't need to invoke `genca` and `gendevcert` commands separately in the correct order.

**Comment by Mendrzec** [comment]
Do you have any ideas already how we could pass the parameters to customize certificate? Currently each command has such usage:
```
-CN, --common-name TEXT         sets common name (CN)
  -O, --organization-name TEXT    sets organization name (O)
  -OU, --organizational-unit-name TEXT sets organizational unit name (OU)
  -L, --locality-name TEXT        sets locality name (L)
  -S, --state-or-province-name TEXT sets state or province name (S)
  -C, --country-name TEXT         sets country name (C)
```
I dont have an idea yet how we should pass params to the  gencerts command. Maybe make it interactive? Ideas are welcome

**Comment by Mendrzec** [comment]
Decided to go with openssl format `"/CN=SomeCn/O=Some organization/..."`
