### ISSUE TITLE
Provide more helpful error message on yaml parsing problems

### ISSUE THREAD

**Issue by wbachnik** [dynatrace-oss/dt-cli#13]
Currently in case there's a problem with parsing `extension.yaml` file user is presented with a stack trace without any hint what's exactly going on. While I don't have a problem with the stacktrace, I believe we should also display a message stating where the problem comes from. Ideally, we should distinguish syntax/formatting problems from missing required fields or unexpected/wrong values.

Ideally, we should report offending line numbers and character positions usually available in [YAMLError](https://pyyaml.org/wiki/PyYAMLDocumentation#yamlerror).

**Comment by allgreed** [comment]
@wbachnik is this still relevant given we have implemented linting support with source (line, column, path) information?

**Comment by allgreed** [comment]
Ok, I see it should've been closed by #28 but wasn't because of a technicality
