### ISSUE TITLE
Provide a windows binary release

### ISSUE THREAD

**Issue by dlopes7** [dynatrace-oss/dt-cli#151]
We should provide a windows standalone binary (like we do for POSIX)

**Comment by bartoszbanachewicz-dynatrace** [comment]
An issue with that might be that `staticx` only supports Linux for now.

**Comment by allgreed** [comment]
@bartoszbanachewicz-dynatrace we don't have to provide an actually static binary for Windows -> we can rely on certain libraries just being there ;) I've read somewhere about decent results running pyinstaller under wine

**Comment by vduseev** [comment]
Preferred solution would be to rewrite the project in Rust, if the project itself makes sense going forward
