### ISSUE TITLE
Click -> typer

### ISSUE THREAD

**Issue by allgreed** [dynatrace-oss/dt-cli#16]
There is something called [Typer](https://github.com/tiangolo/typer), which might be interesting to adopt, especially at this stage of the project development. No strong opinions, just a thought.

Typer advertises itself as better Click and the creator has an excellent track record with FastAPI. Haven't done any major projects with it yet so cannot comment from experience. AFAIK it's interoperable with click's plugin ecosystem.

**Comment by vduseev** [comment]
Just spent half an hour reading through docs and all I can say is that is awesome. We should use it. It's a wrapper on top of click and comes with more strong typing features and other things.

**Comment by allgreed** [comment]
Brought that in scope for Milestone 1

**Comment by allgreed** [comment]
This can be achieved seamlessly actually:
https://typer.tiangolo.com/tutorial/using-click/
