### ISSUE TITLE
Code change in readme-ov-file Usage section

### ISSUE THREAD

**Issue by dannemca-kyndryl** [dynatrace-oss/dt-cli#168]
I was following the procedure to generate my certs and found an typo in this section:
https://github.com/dynatrace-oss/dt-cli?tab=readme-ov-file#usage

```shell
# ii. Generate developer key and certificate from the CA 
$ dt ext generate-developer-pem --ca-crt ca.crt --ca-key ca.key -o dev.pem
# It should be
$ dt ext generate-developer-pem --ca-crt ca.pem --ca-key ca.key -o dev.pem
```

**Comment by vduseev** [comment]
Thank you @dannemca-kyndryl! The typo fix should appear in the next patch release.
