### ISSUE TITLE
Add certificate conversion utility

### ISSUE THREAD

**Issue by allgreed** [dynatrace-oss/dt-cli#17]
This issue is a port of internal issue APM-302358

Currently:
- dctli provides limmited support for dev certificate creation
- however it works quite well [given manual intervention]
- the conversion from ca.key to p12 is missing entirely
`openssl pkcs12 -export -in ca.crt -nokeys -passout pass: -out ca_one.p12`

AC:
- dtcli supports end to end certificate creation and distributions (should distribution be in the scope?)
- reference  plugin implementation (palo alto) uses dtcli to handle the certificates
- documentation mentions using dtcli for dev certificate management

**Comment by allgreed** [comment]
As @wbachnik pointed out, there's no need for the conversion -> since as of now `.pem` is also accepted.

**Comment by airborn** [comment]
Neither `pem` nor `p12` file is not being created by the tool. Only created format is `crt` cannot be uploaded to credentials vault.

**Comment by airborn** [comment]
@Mendrzec could you please reopen?

**Comment by wbachnik** [comment]
Please see #26 - it should solve the confusion.
