### ISSUE TITLE
Same source and target directory leads to extension.zip containing itself

### ISSUE THREAD

**Issue by fpacholczyk** [dynatrace-oss/dt-cli#19]
When the same directory is provided for `--extension-directory` and `--target-directory` parameters, the `dt` tool ends up in a loop, trying to pack `extension.zip` into itself. If any assets (e.g. dashboards) are sufficiently big, it eventually fails leaving `extension.zip` several gigabytes in size.

**Comment by deliego** [comment]
This issue seems to be still happening. I just recreated this issue as well in the latest version from the repository. It created an 11.5 GB zip file which filled up my HD
