### ISSUE TITLE
dt-cli is unable to create extension pack for custom extension on Windows, because of ':' character

### ISSUE THREAD

**Issue by MaciejGrynda** [dynatrace-oss/dt-cli#21]
`.\custom:dtcli-test-1.0.0.zip file already exists, it will be overwritten!
Wrote .\custom:dtcli-test-1.0.0.zip file
Extension built successfuly! :-)`

However, only file that is created is called 'custom'

**Comment by wbachnik** [comment]
That's actually a Windows file system limitation (file names can't contain `:` character). Let's just not use it, and replace with safe alternative like `-` or `_` (I'm in favor of the dash).

**Comment by MaciejGrynda** [comment]
I'm in favour of replacing : with _ on filesystem write - we do the same on EEC
