### ISSUE TITLE
Add flexible configuration options

### ISSUE THREAD

**Issue by vduseev** [dynatrace-oss/dt-cli#3]
## Summary

This ticket covers introduction of config management library to support multiple configuration sources and their merging. 

Configuration sources that should be supported in order of precedence:

* Command line arguments
* Environment variables
* Configuration YAML file specified in command line arguments
* Configuration YAML file in the current working directory
* Default variables

Proposition: use [ilexconf](https://github.com/ilexconf/ilexconf) library.

**Comment by wbachnik** [comment]
That's a great idea. I'm just not sure we need a full library (with additional dependencies) for that. Maybe we can do something simple around click, which is already there?

**Comment by vduseev** [comment]
As far as it goes for ilexconf, it is very lightweight and it's only dependency is Mapz (a convenience wrapper around `dict`, also lightweight), which in turn has no dependencies. Together they implement the simple functionality we'd need for working with several sources of the configuration. `ilexconf` is able to read parameters from different sources and uses `mapz` to merge them in the proper order.

We can do it the other way: use `click`'s ability to read environment variables and implement json/yaml configuration file reader ourselves. Although, Click can't filter environment variables by prefix or understand nested environment variables like Ilexconf does. We'd still need to implement the merging logic, because our parameters can be nested and we won't be able to simply use `dict.extend(other_dict)` to merge them. This is exactly why `ilexconf` exists.

Imagine the following configuration (arbitrary, just for the purposes of showing nested structures).

```yaml
extensions:
  sources:
    - source: my_extension/src/
      file: extension.yml
tenant:
  url: https://<tenant><url>.com
  token: <token> 
```

In order to be able to read non-flat configuration structure from multiple sources (env vars, files, CLI args) we'd need to implement quite a bit of logic around it and then ideally cover it with tests.

P.S. Full disclosure: I've authored ilexconf and mapz after getting tired of doing the same thing for the 10th time when creating CLI applications that read configuration from multiple sources.

**Comment by vduseev** [comment]
Closing because this is out of scope
