### ISSUE TITLE
Overwriting root certificate should be prevented by default

### ISSUE THREAD

**Issue by wbachnik** [dynatrace-oss/dt-cli#6]
Existing root certificate with a matching name should not be overwritten by default. Overwriting it with a newly generated cert should be enabled with a special command line switch (e.g. `--force`).

**Comment by vduseev** [comment]
Makes sense. Verification step and new flag needs to be added.

Just to be sure, we are talking about command that generates CA key pair?

**Comment by wbachnik** [comment]
Yes, that's what I meant. Sorry for the making it clear int he original description.
