### ISSUE TITLE
Use black as a default code formatter for the project?

### ISSUE THREAD

**Issue by wbachnik** [dynatrace-oss/dt-cli#7]
https://github.com/psf/black would that make sense?
I'm not sure how that can be automated, I guess as a PR requirement.

**Comment by vduseev** [comment]
I think we already use it. It is definitely part of the dev dependencies and one thing we could do is to enforce it as a linter rule in the pipeline.

I'd say using black for any OSS python project is the way to go.

**Comment by vduseev** [comment]
Closing as this was added
