### ISSUE TITLE
Embed metadata in zip archive

### ISSUE THREAD

**Issue by wbachnik** [dynatrace-oss/dt-cli#8]
`dt-cli` should embed metadata in the top-level extension zip file, using the [comment field](https://docs.python.org/3/library/zipfile.html#zipfile.ZipFile.comment). Metadata should be formatted as a simple key-value pairs, separated by a newline character. Two fields should be included (with a possibility to add more in the future):
````
Generator: dt-cli <version number>
Creation-time: <current date & UTC time in ISO 8601 format>
````

**Comment by vduseev** [comment]
We currently embed a string in the zip file's comment:

```pythoh
build_time = datetime.datetime.now().strftime("%Y-%m-%d-%H:%M:%S%Z")
build_comment = f"Built by dt-cli ({__version__}) at {build_time}."
```

I like the idea of splitting it by key-value pairs. That makes it more flexible and readable.

**Comment by airborn** [comment]
Currently the comment is placed on internal `extension.zip`  instead of external zip file
