### ISSUE TITLE
Implement secure passphrase handling on the sign command

### ISSUE THREAD

**Issue by allgreed** [dynatrace-oss/dt-cli#81]
The passphrase should be stored in either a password manager or users head.

It should only be prompted for at last possible moment and then purged from memory when used.

Also: remove TODO, near `def sign`

**Comment by allgreed** [comment]
According to my research the only way t o do it sensibly is implement an end to end flow of credentials (so: acquisition, crypto operation, purge) on a platform that allows fine grained memory control (I'm thinking rust or zig) and embedding that into dtcli

**Comment by vduseev** [comment]
Out of scope
