### ISSUE TITLE
How to catch this pesky import bug?

### ISSUE THREAD

**Issue by allgreed** [dynatrace-oss/dt-cli#97]
See `5353c4b308088e9d02133ec82c2118d8bff8ba8f`

```
import dtcli.constants as const

...

def build(**kwargs):
    extension_dir_path = kwargs["extension_directory"]
    const.require_dir_exists(extension_dir_path)
```

Obviously `constants.py` does not contain `require_dir_exists`, but the tooling is oblivious to that fact - flake8, nor mypy just don't see that. Caused #96 

Ideas?

**Comment by allgreed** [comment]
How about mypy --strict?

**Comment by vduseev** [comment]
`mypy --strict` is always a good idea.
