### ISSUE TITLE
Build and sign the extension command on windows 

### ISSUE THREAD

**Issue by Dysio** [dynatrace-oss/dt-cli#99]
After typing command on Windows `dt extension sign --key secrets/developer.pem` error occured
Putting backslash instead forward slash doesn't resolve the issue.
```
ValueError: Error parsing asn1crypto.x509.TbsCertificate - method should have been constructed, but primitive was found
    while parsing asn1crypto.x509.Certificate
```
![image](https://user-images.githubusercontent.com/58117927/179737755-9eccd9be-5ffd-454b-8221-3048b171ed24.png)

**Comment by allgreed** [comment]
Cannot reproduce on GNU/Linux

**Comment by vduseev** [comment]
Can confirm cannot reproduce on IBM AS/400 mostly because I cannot run dt-cli there.

**Comment by eakse** [comment]
issue reproducible on Mac OS Mini running latest version of Monterey

**Comment by allgreed** [comment]
Ok, I've managed to reproduce it. I think it's about the ordering in the fused keycert -> the certificate should be first, followed by the private key.

**Comment by mkokho** [comment]
confirming, if `developer.pem` file has certificate first and the private rsa key second, then `dt extension sign` works.

I used instructions from here https://www.dynatrace.com/support/help/extend-dynatrace/extensions20/sign-extension
I manually moved private rsa key to then end of the file, and successfully built extension.

**Comment by allgreed** [comment]
#114 fixes the certkey generation - it should be the right order now

**Comment by allgreed** [comment]
Proposed course of action:
- if it causes us any more grief in the near future (let's say 1 month from this comment) - programmatically reorder and retry. Otherwise -> leave the error checking and close.

**Comment by mkokho** [comment]
Nice quick fix, thank you! I have tried new version, it works perfectly on Mac

**Comment by vduseev** [comment]
Fixed
